Exposed dataset on website
swapagarwal/swag-for-dev pull request #647
Opened 2020-08-06 05:16 UTC by ARKEOLOGIST

- [X] I've checked that this isn't a new swag opportunity proposal.
- [X] I've checked that this isn't a duplicate pull request.

Made a few minor changes to fix #534
The dataset can now be viewed on-site through the "view data" hyperlink at the bottom of the page.

2020-08-09 09:57 UTC, ARKEOLOGIST commented
Hi, is it possible to get feedback on this?

2020-10-17 02:25 UTC, ARKEOLOGIST commented
@aslafy-z can you have a look at this please?

2020-11-03 19:09 UTC, aslafy-z commented
So sorry, I missed this PR. I'd go with a netlify redirect to GitHub raw, instead of hosting the JSON directly within the website. What do you think @vikaspotluri123?

2020-11-03 19:12 UTC, vikaspotluri123 commented
I agree, can just link to `https://github.com/swapagarwal/swag-for-dev/blob/master/data.json`

2020-11-03 19:51 UTC, ARKEOLOGIST commented
Done the needful.

2020-11-03 19:53 UTC, aslafy-z requested changes

2020-11-03 19:53 UTC, aslafy-z commented on gulpfile.js
> +gulp.task('data', () => {
Please revert these changes

2020-11-03 19:57 UTC, ARKEOLOGIST commented
Done.

2020-11-03 19:58 UTC, ARKEOLOGIST commented on gulpfile.js
> +gulp.task('data', () => {
Done.

2020-11-03 20:39 UTC, aslafy-z commented
Perfect, please rebase on master. Then we will have to rehost Accord project image url to be able to see a preview.

2020-11-03 20:47 UTC, ARKEOLOGIST commented
You might have to rehost the Accord project image URL since it's the one causing the issue in the build.

2020-11-03 20:50 UTC, vikaspotluri123 commented
If you rebase against our master, the build should pass since I added support for failing images in PRs. This allows us to preview and fix the swag image separately

2020-11-03 21:14 UTC, closed without merging