Adding swag opportunity by DeFolio
swapagarwal/swag-for-dev pull request #770
Opened 2020-10-09 04:57 UTC by achaljhawar

resolving issue #717

2020-10-09 04:58 UTC, achaljhawar commented
@vikaspotluri123 is it okay now.

2020-10-09 15:12 UTC, vikaspotluri123 commented on data.json
> +  {
Can you please put this in alphabetical order?

2020-10-09 15:13 UTC, vikaspotluri123 commented on data.json
> +    "name":"DevFolio",
Please update the formatting to follow the rest of the doc (space after colon (`:`))

2020-10-09 15:15 UTC, vikaspotluri123 commented on data.json
> +    "description":"Contribute to any of the following GitHub repositories in october metioned in the article to get stickers and swag from DevFolio shipping only in India.",
```suggestion
    "description": "Contribute 4 valid PRs to one of Devfolio's approved repositories, and receive some stickers! Top 50 contributors will also get a t-shirt.",
```

2020-10-09 15:16 UTC, vikaspotluri123 requested changes
Good start, have a few thing :)

2020-10-09 16:57 UTC, achaljhawar commented
@vikaspotluri123 pls review it again

2020-10-09 17:26 UTC, aslafy-z commented on data.json
> +    {
```suggestion
  {
```

2020-10-09 17:28 UTC, aslafy-z commented on data.json
> +    "image": "https://pbs.twimg.com/media/EJfpSDTUUAIXtdP?format=jpg&name=small",
```suggestion
    "image": "https://pbs.twimg.com/media/EJfpSDTUUAIXtdP.jpg",
```

2020-10-09 17:29 UTC, aslafy-z commented on data.json
> +    "dateAdded": "2020-10-01T16:35:21.000Z",
```suggestion
    "dateAdded": "2020-10-09T16:35:21.000Z",
```

2020-10-16 09:41 UTC, aslafy-z approved these changes
LGTM

2020-10-16 09:44 UTC, aslafy-z commented
Closing in flavor of #732. I did not noticed this duplicate before, sorry for the effort.

2020-10-16 09:44 UTC, closed without merging